"""initial database schema

Revision ID: 20260421_0001
Revises:
Create Date: 2026-04-21
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260421_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def execute_each(statements: Sequence[str]) -> None:
    for statement in statements:
        op.execute(statement)


def upgrade() -> None:
    execute_each(
        [
            """
            CREATE TYPE siuntos_busena AS ENUM (
                'parengta',
                'apmoketa',
                'uzregistruota',
                'ideta',
                'tranzite',
                'pristatyta',
                'atsiimta',
                'atsaukta'
            )
            """,
            "CREATE TYPE siuntos_dydis AS ENUM ('s', 'm', 'l')",
            """
            CREATE TYPE pastomato_busena AS ENUM (
                'aktyvus',
                'neaktyvus',
                'negali_spausdinti',
                'panaikintas'
            )
            """,
            "CREATE TYPE pranesimo_tipas AS ENUM ('sms', 'el_pastas')",
            "CREATE TYPE darbuotojo_pareigos AS ENUM ('administratorius', 'kurjeris')",
            """
            CREATE TABLE asmenys (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                telefono_nr VARCHAR(32) NOT NULL,
                el_pastas VARCHAR(255) NOT NULL,
                vardas VARCHAR(100) NOT NULL,
                pavarde VARCHAR(100) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_asmenys_telefono_nr UNIQUE (telefono_nr),
                CONSTRAINT uq_asmenys_el_pastas UNIQUE (el_pastas)
            )
            """,
            """
            CREATE TABLE siuntejai (
                asmuo_id BIGINT PRIMARY KEY REFERENCES asmenys(id) ON DELETE CASCADE
            )
            """,
            """
            CREATE TABLE gavejai (
                asmuo_id BIGINT PRIMARY KEY REFERENCES asmenys(id) ON DELETE CASCADE
            )
            """,
            """
            CREATE TABLE darbuotojai (
                asmuo_id BIGINT PRIMARY KEY REFERENCES asmenys(id) ON DELETE CASCADE,
                pareigos darbuotojo_pareigos NOT NULL
            )
            """,
            """
            CREATE TABLE pastomatai (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                adresas VARCHAR(255) NOT NULL,
                busena pastomato_busena NOT NULL DEFAULT 'aktyvus',
                produkto_kodas VARCHAR(64) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_pastomatai_produkto_kodas UNIQUE (produkto_kodas)
            )
            """,
            """
            CREATE TABLE pastomato_skyriai (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pastomatas_id BIGINT NOT NULL REFERENCES pastomatai(id) ON DELETE CASCADE,
                dydis siuntos_dydis NOT NULL,
                numeris INTEGER NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_pastomato_skyriai_pastomatas_numeris UNIQUE (pastomatas_id, numeris)
            )
            """,
            """
            CREATE TABLE siuntos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uzsakymo_nr INTEGER NOT NULL,
                siuntejas_id BIGINT NOT NULL REFERENCES siuntejai(asmuo_id) ON DELETE RESTRICT,
                gavejas_id BIGINT NOT NULL REFERENCES gavejai(asmuo_id) ON DELETE RESTRICT,
                pastomato_skyrius_id BIGINT REFERENCES pastomato_skyriai(id) ON DELETE SET NULL,
                dydis siuntos_dydis NOT NULL,
                gavimo_adresas VARCHAR(255) NOT NULL,
                siuntimo_adresas VARCHAR(255) NOT NULL,
                data DATE NOT NULL,
                busena siuntos_busena NOT NULL DEFAULT 'parengta',
                siuntos_kodas VARCHAR(64) NOT NULL,
                suma NUMERIC(10, 2) NOT NULL,
                saskaita VARCHAR(255),
                apmokamas_pastomate BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_siuntos_uzsakymo_nr UNIQUE (uzsakymo_nr),
                CONSTRAINT uq_siuntos_siuntos_kodas UNIQUE (siuntos_kodas),
                CONSTRAINT uq_siuntos_pastomato_skyrius UNIQUE (pastomato_skyrius_id),
                CONSTRAINT ck_siuntos_suma_neneigiama CHECK (suma >= 0)
            )
            """,
            "CREATE INDEX ix_siuntos_siuntejas_id ON siuntos(siuntejas_id)",
            "CREATE INDEX ix_siuntos_gavejas_id ON siuntos(gavejas_id)",
            "CREATE INDEX ix_siuntos_busena ON siuntos(busena)",
            """
            CREATE TABLE pranesimai (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                asmuo_id BIGINT NOT NULL REFERENCES asmenys(id) ON DELETE CASCADE,
                tekstas TEXT NOT NULL,
                tipas pranesimo_tipas NOT NULL,
                issiuntimo_operatoriui_data DATE,
                operatoriaus_atsako_data DATE,
                issiustas BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )
            """,
            "CREATE INDEX ix_pranesimai_asmuo_id ON pranesimai(asmuo_id)",
            "CREATE INDEX ix_pranesimai_issiustas ON pranesimai(issiustas)",
        ]
    )


def downgrade() -> None:
    execute_each(
        [
            "DROP TABLE IF EXISTS pranesimai",
            "DROP TABLE IF EXISTS siuntos",
            "DROP TABLE IF EXISTS pastomato_skyriai",
            "DROP TABLE IF EXISTS pastomatai",
            "DROP TABLE IF EXISTS darbuotojai",
            "DROP TABLE IF EXISTS gavejai",
            "DROP TABLE IF EXISTS siuntejai",
            "DROP TABLE IF EXISTS asmenys",
            "DROP TYPE IF EXISTS darbuotojo_pareigos",
            "DROP TYPE IF EXISTS pranesimo_tipas",
            "DROP TYPE IF EXISTS pastomato_busena",
            "DROP TYPE IF EXISTS siuntos_dydis",
            "DROP TYPE IF EXISTS siuntos_busena",
        ]
    )
