"""describe change

Revision ID: bb8ef2a88670
Revises: 21bc34c96071
Create Date: 2026-04-21 20:08:59.245961
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'bb8ef2a88670'
down_revision: str | None = '21bc34c96071'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
